In [5]:
import numpy as np
import pandas as pd

s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

In [6]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [7]:
demo_array = np.arange(10,17)

demo_array [:]= 101

demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [8]:
   demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [16]:
football = [24, 235, 34, 456, 65, 67]
print(football)
np.array(football)

[24, 235, 34, 456, 65, 67]


array([ 24, 235,  34, 456,  65,  67])

In [11]:
score = [10, 15, 20, 25]

pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [13]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [14]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347