In [5]:
import numpy as np

l1 = [1,2,3,4]
nd1 = np.array(l1)

print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(nd2.shape)
print(nd2.size)
print(nd2.dtype)


(2, 4)
8
int64


In [15]:
nd3 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(nd3)

l1 = [9,8,7]
l2 = [6,5,4]
l3 = [3,2,1]
nd3 = np.array([l1,l2,l3])
print(nd3)
print(nd3.T)
print(nd3+1)
print(nd3*2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 6 3]
 [8 5 2]
 [7 4 1]]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
[[18 16 14]
 [12 10  8]
 [ 6  4  2]]


In [17]:
nd6 = np.array([[1,4,9,121,144,169],[16,25,36,196,255,256],[49,64,81,289,324,361]])
print(nd6)
print(nd6.mean())

[[  1   4   9 121 144 169]
 [ 16  25  36 196 255 256]
 [ 49  64  81 289 324 361]]
133.33333333333334


In [22]:
print(np.dot(nd2,nd1))

[30 70]


In [25]:
x = np.arange(20)
x
print(x[:5])

[0 1 2 3 4]


In [27]:
print(x[1::2])

[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
print(x[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
