In [1]:
import numpy as np

cosine = np.cos(np.pi)
print(cosine)
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [5]:
#create numpy array using list, which is vector
vec = np.array([1,2,3])
print(vec)

#create martices using numpy
mat = np.array([[1,2,1],[4,5,8],[3,2,1]])
print(mat)
print('')
print(mat.T)

[1 2 3]
[[1 2 1]
 [4 5 8]
 [3 2 1]]

[[1 4 3]
 [2 5 2]
 [1 8 1]]


In [7]:
#other ways to create array using arange
vec2 = np.arange(0,15)
print(vec2)
print('')

vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [16]:
vec4 = np.linspace(0,5,10)
print(vec4)

vec_reshape = vec4.reshape(5,2)
print(vec_reshape)
print(vec4)
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones([5,3])
print(mat3)
mat4 = np.eye(5)
print(mat4)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [18]:
#matric multiplication
print(mat)
print('')
print(vec)
print('')
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 8]
 [3 2 1]]

[1 2 3]

[ 8 38 10]


In [20]:
print(np.linalg.solve(mat, product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[-5.00000000e-01  4.16333634e-17  5.00000000e-01]
 [ 9.09090909e-01 -9.09090909e-02 -1.81818182e-01]
 [-3.18181818e-01  1.81818182e-01 -1.36363636e-01]]


In [21]:
#find unique values from array
vec7 = np.array(['blue', 'red', 'orange', 'purple','purple','orange','red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'red' '6']
['6' 'blue' 'orange' 'purple' 'red']


In [23]:
#use numpy to create samples
rand_mat = np.random.rand(5,5) #uniform random variables
print(rand_mat)

rand_mat2 = np.random.randn(5,5) #standard random variables
print(rand_mat2)


[[0.78038551 0.95533489 0.79018509 0.48314291 0.56990375]
 [0.89103375 0.84086027 0.19579285 0.39340715 0.9082052 ]
 [0.0550474  0.24701512 0.53906046 0.7580052  0.8398436 ]
 [0.33213665 0.64268508 0.57348013 0.29799943 0.11242188]
 [0.64951647 0.64988107 0.47209524 0.28794221 0.67013866]]
[[-1.68538538  2.42841147  0.51500811  0.37863073  0.19500524]
 [-0.08375247  0.82761359  0.37026075  0.47986546 -0.35920741]
 [ 0.52922486  0.28349713 -0.02719864  1.13708426 -0.55882749]
 [-2.07604315 -0.66840431  1.25370244  0.92439497  1.35867195]
 [ 0.99686184 -0.33851152 -0.73473505  0.30576196 -1.09532433]]


In [24]:
#statistical tools
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5574207991116994
0.9705727784190276


In [26]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.05504740300519162
2.4284114673679067
