In [3]:
import numpy as np
print(np.cos(np.pi))


-1.0


In [5]:
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))
print(np.log(6))
print(np.exp(4))

1.1
5.2
1.791759469228055
54.598150033144236


In [6]:
#we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)

#we can create matrices by converting list of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('********')
print(mat)
print('********')
print(mat.T) #This is transpose of a matrix

[1 2 3]
********
[[1 2 1]
 [4 5 9]
 [1 8 9]]
********
[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [7]:
#other ways to create array
vec2 = np.arange(0,15)
print(vec2)
print('*******')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
*******
[ 3  9 15]


In [9]:
vec4 = np.linspace(0,5,10) # linear space starting and stoping point is inclusive, third point is must
print(vec4)
print('********')
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
********
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [19]:
#create numpy array with number of zeros
mat2 = np.zeros([5,3])
print(mat2)
print('***********')

mat3 = np.ones((3,5))
print(mat3)
print('***********')
mat4 = np.eye(5) #main diagonal will have 1
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
***********
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
***********
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5 + vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [24]:
#matrix multuplication
print(mat)
print('')
print(vec)
print('')
product = np.matmul(mat, vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [25]:
print(np.linalg.solve(mat, product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [26]:
np.log(6)

1.791759469228055

In [30]:
np.exp(4)


54.598150033144236

In [29]:
np.sqrt(1.44)

1.2

In [31]:
arr = np.arange(4,20,5)
print(arr)

[ 4  9 14 19]


In [32]:
#how to you access entries in numpy vector
rand_vector = np.random.rand(19)
print(rand_vector)

[0.77772938 0.74075469 0.64198565 0.02557853 0.55163146 0.58025577
 0.43686203 0.42935376 0.11559499 0.15495584 0.04207481 0.4477258
 0.04676171 0.03838486 0.89529926 0.61947616 0.03742144 0.56606287
 0.9469042 ]


In [35]:
print(rand_vector[6])

0.43686203389939615


In [36]:
print(rand_vector[4:9])

[0.55163146 0.58025577 0.43686203 0.42935376 0.11559499]


In [40]:
print(np.arange(0,15,3))
print(rand_vector[np.arange(0,15,3)])

[ 0  3  6  9 12]
[0.77772938 0.02557853 0.43686203 0.15495584 0.04676171]


In [44]:
print(mat)
print(mat[1][2])
print(mat[1,2])
print(mat[0:1,1:3])

[[1 2 1]
 [4 5 9]
 [1 8 9]]
9
9
[[2 1]]


In [45]:
#change values in array & matrics
print(rand_vector)
rand_vector[3:5] = 4
print(rand_vector)

[0.77772938 0.74075469 0.64198565 0.02557853 0.55163146 0.58025577
 0.43686203 0.42935376 0.11559499 0.15495584 0.04207481 0.4477258
 0.04676171 0.03838486 0.89529926 0.61947616 0.03742144 0.56606287
 0.9469042 ]
[0.77772938 0.74075469 0.64198565 4.         4.         0.58025577
 0.43686203 0.42935376 0.11559499 0.15495584 0.04207481 0.4477258
 0.04676171 0.03838486 0.89529926 0.61947616 0.03742144 0.56606287
 0.9469042 ]


In [46]:
rand_vector[3:5] = [1,2]
print(rand_vector)

[0.77772938 0.74075469 0.64198565 1.         2.         0.58025577
 0.43686203 0.42935376 0.11559499 0.15495584 0.04207481 0.4477258
 0.04676171 0.03838486 0.89529926 0.61947616 0.03742144 0.56606287
 0.9469042 ]


In [48]:
sub_mat = mat[0:2, 0:3]
sub_mat[:] = 99
print(sub_mat)
print(mat)

sub_mat2 = mat[0:2, 0:3].copy()
sub_mat2[:] = 33
print(sub_mat2)
print(mat)

[[99 99 99]
 [99 99 99]]
[[99 99 99]
 [99 99 99]
 [ 1  8  9]]
[[33 33 33]
 [33 33 33]]
[[99 99 99]
 [99 99 99]
 [ 1  8  9]]


In [49]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix[1][1])

5


In [50]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:

arr = np.arange(4, 20, 5)

print(arr)

[ 4  9 14 19]


In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix[1][1])

5


In [8]:
matrix = np.array([[-1, 2, 3], [4, -5, 6], [7, -8, 9]])

print(matrix[matrix>0])

[2 3 4 6 7 9]


In [9]:
loaded_array = np.load('matrix.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'matrix.npy'